using System.Reflection;
using System.Text;

namespace CDS.ScriptChat.Core;

/// <summary>
/// Works out what a script can reach from its globals type, and lists it by name — the index a
/// host puts in <see cref="ScriptChatSessionOptions.OrientationBlurb"/> so the model knows what
/// exists before asking <c>lookup_symbol</c> what any of it looks like.
/// </summary>
/// <remarks>
/// <para>
/// Generated by reflection rather than hand-written, so it cannot drift from the code. Names only,
/// deliberately: signatures and documentation are fetched on demand, which keeps the index short
/// and keeps the detail accurate.
/// </para>
/// <para>
/// <see cref="ScriptFacingTypes(Type, Type[])"/> returns exactly the set
/// <see cref="Describe(Type, Type[])"/> lists, so a host that feeds both from one call cannot end
/// up telling the model something exists that it then cannot ask about.
/// </para>
/// <para>
/// Nothing here is specific to any host, and it takes no dependency beyond the BCL — a
/// consumer's own globals type, with its own API class, indexes exactly as any other.
/// </para>
/// </remarks>
public static class HostApiIndex
{
    /// <summary>
    /// The conventional name of the property a script-facing UI class keeps its own API behind,
    /// so the useful members are not buried among the hundreds a control inherits.
    /// </summary>
    public const string DefaultFacadePropertyName = "API";

    /// <summary>
    /// Members every type has, which say nothing about what a host offers.
    /// </summary>
    private static readonly HashSet<string> s_uninterestingMembers =
        new(StringComparer.Ordinal) { "ToString", "Equals", "GetHashCode", "GetType", "Dispose" };

    /// <summary>
    /// The types a script normally starts from: the root type itself, whatever it exposes, and
    /// the facades any of those keep their members behind.
    /// </summary>
    /// <param name="rootType">
    /// The globals type the script is compiled against, or — for a host with one flat API class
    /// and no globals — that class.
    /// </param>
    /// <param name="additionalTypes">
    /// Types a script works with that <paramref name="rootType"/> does not itself expose,
    /// typically the panel and component types its properties hand out results through.
    /// </param>
    /// <returns>The types, in the order a reader would meet them, without duplicates.</returns>
    /// <exception cref="ArgumentNullException">Either argument is <see langword="null"/>.</exception>
    /// <remarks>
    /// The root type's properties are followed one level deep and no further. A host names what
    /// else matters explicitly, rather than this walking an object graph it cannot know the shape
    /// of and burying the useful entries.
    /// </remarks>
    public static IReadOnlyList<Type> ScriptFacingTypes(Type rootType, params Type[] additionalTypes) =>
        ScriptFacingTypes(rootType, DefaultFacadePropertyName, additionalTypes);

    /// <summary>
    /// The types a script normally starts from, for a host whose facade property is not called
    /// <see cref="DefaultFacadePropertyName"/>.
    /// </summary>
    /// <param name="rootType">The globals type, or a flat API class.</param>
    /// <param name="facadePropertyName">
    /// The property name a class keeps its own API behind, or <see langword="null"/> to follow no
    /// facade at all.
    /// </param>
    /// <param name="additionalTypes">Types the script works with that the root does not expose.</param>
    /// <returns>The types, in the order a reader would meet them, without duplicates.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="rootType"/> or <paramref name="additionalTypes"/> is <see langword="null"/>.</exception>
    public static IReadOnlyList<Type> ScriptFacingTypes(
        Type rootType,
        string? facadePropertyName,
        params Type[] additionalTypes) =>
        [.. Entries(rootType, facadePropertyName, additionalTypes).Select(entry => entry.Type)];

    /// <summary>
    /// Lists the names of everything a script can reach, as markdown bullets — one line per type.
    /// </summary>
    /// <param name="rootType">The globals type, or a flat API class.</param>
    /// <param name="additionalTypes">The panel and component types the script also works with.</param>
    /// <returns>The index. Wrap it in whatever prose the host wants around it.</returns>
    /// <exception cref="ArgumentNullException">Either argument is <see langword="null"/>.</exception>
    /// <remarks>
    /// Each type a root property hands out is labelled with the <em>property</em> name rather than
    /// the type name, because that is what a script author types: a property called <c>API</c>
    /// returning a <c>WorkspaceApi</c> is listed as <c>API</c>, since <c>API.CreateImagePanel(...)</c>
    /// is how it is actually called.
    /// </remarks>
    public static string Describe(Type rootType, params Type[] additionalTypes) =>
        Describe(rootType, DefaultFacadePropertyName, additionalTypes);

    /// <summary>
    /// Lists the names of everything a script can reach, for a host whose facade property is not
    /// called <see cref="DefaultFacadePropertyName"/>.
    /// </summary>
    /// <param name="rootType">The globals type, or a flat API class.</param>
    /// <param name="facadePropertyName">
    /// The property name a class keeps its own API behind, or <see langword="null"/> to follow no
    /// facade at all.
    /// </param>
    /// <param name="additionalTypes">The panel and component types the script also works with.</param>
    /// <returns>The index. Wrap it in whatever prose the host wants around it.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="rootType"/> or <paramref name="additionalTypes"/> is <see langword="null"/>.</exception>
    public static string Describe(Type rootType, string? facadePropertyName, params Type[] additionalTypes)
    {
        var builder = new StringBuilder();

        foreach (var (label, type) in Entries(rootType, facadePropertyName, additionalTypes))
        {
            var names = MemberNames(type).ToArray();

            if (names.Length > 0)
            {
                builder.AppendLine($"- `{label}`: {string.Join(", ", names)}");
            }
        }

        return builder.ToString();
    }

    /// <summary>
    /// The public instance members of one type that a script author would recognise: declared on
    /// the type itself, with accessors, constructors and the universal <see cref="object"/>
    /// members left out.
    /// </summary>
    /// <param name="type">The type to list.</param>
    /// <returns>The member names, without duplicates, in alphabetical order.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="type"/> is <see langword="null"/>.</exception>
    /// <remarks>
    /// <see cref="BindingFlags.DeclaredOnly"/> matters for UI types: a panel deriving from a
    /// framework control would otherwise list several hundred inherited members and bury the
    /// handful that are the point.
    /// </remarks>
    public static IEnumerable<string> MemberNames(Type type)
    {
        ArgumentNullException.ThrowIfNull(type);

        return type.GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Where(IsScriptFacing)
            .Select(member => member.Name)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal);
    }

    /// <summary>
    /// The labelled types both public members are built from, so the index a model is given and
    /// the set searched when it asks about a bare member name cannot drift apart.
    /// </summary>
    private static IEnumerable<(string Label, Type Type)> Entries(
        Type rootType,
        string? facadePropertyName,
        Type[] additionalTypes)
    {
        ArgumentNullException.ThrowIfNull(rootType);
        ArgumentNullException.ThrowIfNull(additionalTypes);

        var seen = new HashSet<Type> { rootType };

        // The root itself comes first. Without this, a host with one flat API class and no
        // globals indirection gets an empty index — the commonest shape there is, and it failed
        // silently. It also surfaces the plain data a globals type carries alongside its API
        // (an int threshold, a bool switch), which a script reaches by name and which nothing
        // else in this walk would mention.
        //
        // Its facade is deliberately not followed here: the property walk below reaches the same
        // type and labels it with the property name a script author actually types — `API`, not
        // `MyGlobals.API`.
        yield return (rootType.Name, rootType);

        foreach (var entry in Candidates(rootType, additionalTypes))
        {
            if (!seen.Add(entry.Type))
            {
                continue;
            }

            yield return entry;

            if (Facade(entry.Type, facadePropertyName) is { } facade && seen.Add(facade))
            {
                yield return ($"{entry.Label}.{facadePropertyName}", facade);
            }
        }
    }

    private static IEnumerable<(string Label, Type Type)> Candidates(Type rootType, Type[] additionalTypes)
    {
        // Labelled by property name: a script reaches these by writing the property, not the type.
        foreach (var property in ScriptFacingProperties(rootType))
        {
            yield return (property.Name, property.PropertyType);
        }

        foreach (var additional in additionalTypes)
        {
            ArgumentNullException.ThrowIfNull(additional);
            yield return (additional.Name, additional);
        }
    }

    /// <summary>
    /// The properties of a root type worth following into: the ones returning a host's own
    /// classes.
    /// </summary>
    /// <remarks>
    /// A globals type routinely carries plain data alongside its API — an <c>int</c> threshold, a
    /// <c>bool</c> switch, the run's <see cref="CancellationToken"/>. Listing the members of those
    /// is noise: what the model needs from them is that they exist, which the root type's own
    /// entry now says.
    /// </remarks>
    private static IEnumerable<PropertyInfo> ScriptFacingProperties(Type rootType) =>
        rootType
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(property => property.GetIndexParameters().Length == 0 && IsHostType(property.PropertyType));

    /// <summary>
    /// True for a type a host declares itself, false for the framework's own. Namespace is the
    /// only signal available — an assembly-based test would exclude a host's types that happen to
    /// live in the same assembly as this library's.
    /// </summary>
    private static bool IsHostType(Type type)
    {
        if (type.IsPrimitive || type.IsEnum || type == typeof(string) || type == typeof(object))
        {
            return false;
        }

        var space = type.Namespace;

        return space is not null
            && !space.StartsWith("System", StringComparison.Ordinal)
            && !space.StartsWith("Microsoft", StringComparison.Ordinal);
    }

    /// <summary>The type of a class's facade property, or null when it has none.</summary>
    private static Type? Facade(Type type, string? facadePropertyName) =>
        string.IsNullOrEmpty(facadePropertyName)
            ? null
            : type.GetProperty(facadePropertyName)?.PropertyType;

    private static bool IsScriptFacing(MemberInfo member)
    {
        // IsSpecialName covers property getters and setters, event add and remove, and operators.
        // Nested types are listed as members too, which is how a panel's own facade type would
        // otherwise appear alongside the API property that returns it.
        if (member is ConstructorInfo or Type || member is MethodBase { IsSpecialName: true })
        {
            return false;
        }

        // Compiler-generated backing members are named with angle brackets, which no C# identifier
        // can contain.
        return !member.Name.StartsWith('<') && !s_uninterestingMembers.Contains(member.Name);
    }
}
